### ISSUE TITLE
Fix shifted marks

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Archivo#10]
I can see that some marks have shifted (look at the dotbelow glyphs). I need these fixed before I can PR.

I understand the Vietnamese ones are ok.

![archivo_dotbelow](https://user-images.githubusercontent.com/7525512/45618746-b7f11880-ba6e-11e8-8ade-590187ee9f62.gif)

Here's the GFR [link](http://www.gf-regression.com/screenshot/f119d684-b581-42cd-ba28-21a4b70e24e8/glyphs-all/after/48) which should help you.

**Comment by m4rc1e** [comment]
cc @davelab6

**Comment by davelab6** [comment]
So great to see our investment in tooling pay off

**Comment by m4rc1e** [comment]
@Omnibus-Type Have we fixed this?

**Comment by Omnibus-Type** [comment]
Yes @m4rc1e Marc, we have fixed a few days ago.

**Comment by m4rc1e** [comment]
Thanks! closing. Will pr now.
