### ISSUE TITLE
Can we drop the reserved font names?

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Archivo#11]
This family has a reserved font name. This is visible in the copyright.

> Copyright 2018 The Archivo Project Authors (https://github.com/Omnibus-Type/Archivo) with Reserved Font Name "Archivo".

The version we currently serve on Google Fonts doesn't have this reserve font name so its copyright is:

> Copyright 2017 The Archivo Project Authors (https://github.com/Omnibus-Type/Archivo)

Can we please drop it?

**Comment by Omnibus-Type** [comment]
Updated!
