### ISSUE TITLE
Italic naming failed

### ISSUE THREAD

**Issue by NightFurySL2001** [Omnibus-Type/Archivo#14]
Same as https://github.com/Omnibus-Type/Saira/issues/15.

Roman:
![image](https://user-images.githubusercontent.com/33471049/104476380-245a9300-55fb-11eb-90f4-0f759876117a.png)

Italic:
![image](https://user-images.githubusercontent.com/33471049/104476455-3805f980-55fb-11eb-8574-dfd86e7be4f6.png)

**Comment by Omnibus-Type** [comment]
Yes, Saira is our model project for Archive and other fonts for the Omnibus-Type catalog, therefore the problem is recurring. Soon I will be making the corresponding files and updating some repositories. Thanks again.

**Comment by NightFurySL2001** [comment]
Thanks for fixing the issue!
