### ISSUE TITLE
Regression issue

### ISSUE THREAD

**Issue by RosaWagner** [Omnibus-Type/Archivo#16]
One vertical metric issue still remain, but I will fix it ;)

Otherwise I observe regressions issue for the weight. Is it okay if I make the weight like current GF version to avoid complain from users, or it is important for you that the new version has a thicker weight?

![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/12222436/105490088-8e86ce00-5cb4-11eb-95f8-3ef21f5e6259.gif)

**Comment by Omnibus-Type** [comment]
Hi @RosaWagner, many thanks!
When mastering the entire Archive project, some aspects of the drawings were updated and corrected, we decided to make the instances with a linear method, to avoid possible conflicts with Fontbakery, at that time the issue of axis mapping was still under discussion, which modified the weight in some cases. We agree that it should be the closest to what is published on GF, to avoid any problem with the user.

Fontbakery suggest to increase the Bbox metrics to the values (1092 and 410 for Ascenders and Descenders respectively) but differs from the one published in GF (878 and 210 for Ascenders and Descenders respectively). It will be possible that Fontbakery marks it again as an issue?

**Comment by RosaWagner** [comment]
Ah, no with the "use_typo_metric" flag, it will look at typoAscender and typoDescender (which as to be the same as previous version), then, WinAscent and Windescent have to correspond to the lowest and highest glyphs to avoid text clipping in browsers. 

So ok, I do the axis mapping thing to match previous version ;)

**Comment by Omnibus-Type** [comment]
Many thanks Rosa!
