### ISSUE TITLE
Still two style group errors

### ISSUE THREAD

**Issue by kenmcd** [Omnibus-Type/Archivo#19]
There are still two styling groups errors caused by trailing spaces in the styling group name.
This puts these two Italic fonts in a different group than their related Regular.

- Archivo ExtraCondensed Light Italic
- Archivo SemiCondensed SemiBold Italic

Remove those trailing spaces and the entire family looks good.

**Comment by Yorlmar** [comment]
I have Fixed it. Thanks for the advice!

**Comment by kenmcd** [comment]
Lookin' good now!
