### ISSUE TITLE
Consolidate Archivo families

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Archivo#5]
It would be nice to consolidate the 3 families into one coherent super family.

If we do this, we'll get a variable font which has both a weight and width axis.

**Comment by Omnibus-Type** [comment]
We agree and we'll work on that soon. We are interested in producing new Archivo Condensed and Archivo Compressed subfamilies. Archivo Narrow has predetermined widths (lowercase letters are more condensed than uppercase letters) that must be maintained.

**Comment by cssobral2013** [comment]
One more suggestion: add more weights (Light, Thin, ExtraBold...)

**Comment by Omnibus-Type** [comment]
On the way!
