### ISSUE TITLE
Missing glyphs

### ISSUE THREAD

**Issue by m4rc1e** [Omnibus-Type/Archivo#9]
Family is missing the following glyphs:

![screen shot 2018-09-03 at 14 10 40](https://user-images.githubusercontent.com/7525512/44988593-28823a80-af83-11e8-9fcb-559c44a09fd2.png)

http://www.gf-regression.com/compare/b63d22cf-8857-4b6c-a81d-30276b87949e

We need them added before I can pr the family to google/fonts

**Comment by Omnibus-Type** [comment]
Done! Thanks :)

**Comment by m4rc1e** [comment]
Thanks
